## Demo PCA

In [1]:
import numpy as np
from numpy.linalg import eig
from numpy import array
from sklearn.decomposition import PCA

#### Define the sample array 'A'

In [8]:
A = np.array([[1,2,], [3,4],[5,6]])

print(f"A:\n\n{A}")

A:

[[1 2]
 [3 4]
 [5 6]]


### Calculate the mean, 'M' of 'A' and subtract the 'M' from 'A' to compute 'C':

In [9]:
M = np.mean(A.T, axis=1)
C = A - M

print(f"M:\n\n{M}\n\n")
print(f"C:\n\n{C}\n\n")

M:

[3. 4.]


C:

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]




### Compute the covariance, 'V' of 'C':

In [10]:
V = np.cov(C.T)

print(f"V:\n\n{V}\n\n")

V:

[[4. 4.]
 [4. 4.]]




### Compute eigendecomposition of covariance matrix, 'V':
This will create:
 - eigen-values
 - eigen-vectors

In [11]:
values, vectors = eig(V)
print(f"eigen-values:\n\n{values}\n\n")
print(f"eigen-vectors:\n\n{vectors}\n\n")

eigen-values:

[8. 0.]


eigen-vectors:

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]




### Project the data

In [12]:
P = vectors.T.dot(C.T)
print(f"P.T:\n\n{P.T}\n\n")

P.T:

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]




### Now use sklearn PCA to confirm the results 

In [15]:
def computePcaResults(A: np.array) -> np.array:
    """
    """
    dim = A.shape[1]
    pca = PCA(n_components=dim)
    pca.fit(A)
    A_hat = pca.transform(A)
    return A_hat

A_hat = computePcaResults(A)

print(f"A_hat:\n\n{A_hat}\n\n")

A_hat:

[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]


